apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-11-19T16:45:50Z"
  generation: 9
  labels:
    app: sftp-server
  name: sftp-server
  namespace: test-project
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: sftp-server
    deploymentconfig: sftp-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: sftp-server
        deploymentconfig: sftp-server
    spec:
      containers:
      - image: docker-registry.default.svc:5000/test-project/sftp-server@sha256:f727c0f5bae83e25ae7f588b333c94c3af3fbc0f86e9985b845241f4ae22a9e7
        imagePullPolicy: Always
        name: sftp-server
        ports:
        - containerPort: 2222
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/timbube/.ssh/authorized_keys
          name: volume-r5cjm
          subPath: authorized_keys
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - chown
        - "100"
        - /tmp/authorized_keys
        image: alpine:latest
        imagePullPolicy: Always
        name: install
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/authorized_keys
          name: volume-r5cjm
          subPath: authorized_keys
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 100
      serviceAccount: sftp-sa
      serviceAccountName: sftp-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 384
          name: pub-key
        name: volume-r5cjm
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - sftp-server
      from:
        kind: ImageStreamTag
        name: sftp-server:latest
        namespace: test-project
      lastTriggeredImage: docker-registry.default.svc:5000/test-project/sftp-server@sha256:f727c0f5bae83e25ae7f588b333c94c3af3fbc0f86e9985b845241f4ae22a9e7
    type: ImageChange
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: "2020-11-19T16:55:22Z"
    lastUpdateTime: "2020-11-19T16:55:22Z"
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
  - lastTransitionTime: "2020-11-19T16:57:52Z"
    lastUpdateTime: "2020-11-19T16:57:52Z"
    message: replication controller "sftp-server-6" is progressing
    reason: ReplicationControllerUpdated
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 6
  observedGeneration: 9
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
