apiVersion: v1
kind: Service
metadata:
  labels:
    app: sftpserver
  name: sftpserver
spec:
  ports:
    - name: 2222-tcp
      nodePort: 30683
      port: 2222
      protocol: TCP
      targetPort: 2222
  selector:
    deploymentconfig: sftpserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
