apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sftpserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: <storageclass-name>
